#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Install necessary packages

apt update > /dev/null 2>&1 && apt install curl -y > /dev/null 2>&1

# Retrieve files

curl -Ls https://github.com/bugy/script-server/archive/dev.tar.gz | tar xz --strip 1 -C /app > /dev/null 2>&1

# Install dependencies

curl -Ls https://raw.githubusercontent.com/bugy/script-server/master/requirements.txt | pip install -r /dev/stdin

# Create user to run web facing server

adduser --disabled-login --no-create-home --gecos "" tornado > /dev/null 2>&1

# Retrieve web files

/app/tools/init.py --no-npm > /dev/null 2>&1

# Fix permissions

groupmod -o -g "$PGID" tornado > /dev/null 2>&1
usermod -o -u "$PUID" tornado > /dev/null 2>&1

chown -R tornado:tornado /app


